config/routes.rb
Rails.application.routes.draw do
  resources :types, only: [:new, :create]
  resources :billings, except: [:index]
  resources :users, only: [:new, :create, :show, :update, :edit, :destroy]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  root 'sessions#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :user
  belongs_to :type

  validates :fix_or_var, inclusion:{in: %w(fixed variable)}

  def type_name=(name)
    self.type = Type.find_or_create_by(name: name)
  end

  def type_name
    self.type ? self.type.name : nil
  end
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :billings
  has_many :users, through: :billings

  validates :name, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :billings
  has_many :types, through: :billings
  has_secure_password
  before_save :downcase_email

  validates :email, uniqueness:true

  def downcase_email
    self.email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user
  helper_method :current_user
  helper_method :required_login
  helper_method :login?
  helper_method :skip_login
  def current_user
    @user = User.find_by(email: session[:user_email]) || User.new
  end

  def login?
    current_user.id != nil
  end

  def required_login
    return redirect_to(controller: 'sessions', action: 'new') unless login?
  end

  def skip_login
    if login?
      redirect_to user_path(current_user)
    end
  end
end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController
  before_action :current_user
  def show
    @billing = Billing.find(params[:id])
  end

  def new
    @billing = Billing.new
  end

  def create
    @billing = current_user.billings.create(billing_params)
    return render :new unless @billing.save
    redirect_to user_path(current_user)
  end

  def edit
    @billing = Billing.find(params[:id])
  end

  def update
    @billing = Billing.find(params[:id])
    @billing.update(billing_params)
    return render :edit unless @billing.save
    redirect_to user_path(current_user)

  end

  def destroy
    @billing = Billing.find(params[:id])
    @billing.delete
    redirect_to user_path(current_user)
  end

  private
    def billing_params
      params.require(:billing).permit(:description, :date, :type_name, :fix_or_var)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :skip_login, only: [:new]

  def new

  end

  def create
    user = User.find_by(email: params[:user][:email])
    authenticate = user.try(:authenticate, params[:user][:password])
    return redirect_to controller: 'sessions', action: 'new' unless authenticate
    session[:user_email] = user.email
    @user = user
    redirect_to user_path(@user)
  end

  def destroy
    session.delete :user_email

    redirect_to '/'
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :required_login, except: [:new, :create]
  def show

  end

  def new

  end

  def create
    @user = User.create(user_params)
    return render :new unless @user.save
    session[:user_email] = @user.email
    redirect_to user_path(@user)
  end

  def update
    @user = current_user
    @user.update(user_params)
    return render :edit unless @user.save
  end

  def edit

  end

  private
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/billings/edit.html.erb
<div class="container-fluid">
  <div class="d-flex justify-content-center login">
    <div class="border">
      <div class="form-header">
        <h4>Edit Billing</h4>
      </div>
      <%= form_for @billing do |f| %>
      <div class="field_with_errors form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class:"form-control" %>
      </div>
      <div class="field_with_errors form-group">
        <%= f.label :date %>
        <%= f.date_select(:date, :order => [:month, :day, :year], class:"form-control") %>
      </div>
      <div class="field_with_errors form-group">
        <%= f.label :type_name %>
        <%= f.text_field :type_name, list: 'type_autocomplete', class:"form-control"%>
          <datalist id="type_autocomplete">
            <% Type.all.each do |type| %>
              <option value="<%= type.name %>">
            <% end %>
          </datalist>
      </div>
      <div class="field_with_errors form-group">
        <%= f.label :fix_or_var %>
        <%= f.text_field :fix_or_var, class:"form-control" %>
      </div>
      <div class="submit">
        <%= f.submit "Confirm Changes", class:'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/billings/new.html.erb
<div class="container-fluid">
  <div class="d-flex justify-content-center login">
    <div class="border">
      <div class="form-header">
        <h4>Add A Billing</h4>
      </div>
      <%= form_for @billing do |f| %>
      <div class="field_with_errors form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class:"form-control" %>
      </div>
      <div class="field_with_errors form-group">
        <%= f.label :date %>
        <%= f.date_select(:date, :order => [:month, :day, :year], class:"form-control") %>
      </div>
      <div class="field_with_errors form-group">
        <%= f.label :type_name %>
        <%= f.text_field :type_name, list: 'type_autocomplete', class:"form-control"%>
          <datalist id="type_autocomplete">
            <% Type.all.each do |type| %>
              <option value="<%= type.name %>">
            <% end %>
          </datalist>
      </div>
      <div class="field_with_errors form-group">
        <%= f.label :fix_or_var %>
        <%= f.text_field :fix_or_var, class:"form-control" %>
      </div>
      <div class="submit">
        <%= f.submit "Create", class:'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/billings/show.html.erb
<div class="container-fluid">
  <div class="d-flex justify-content-center login">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Type: <%= @billing.type_name %></li>
      <li class="list-group-item">Description: <%= @billing.description %></li>
      <li class="list-group-item">Date: <%= @billing.date %></li>
      <li class="list-group-item">Fix Or Variable: <%= @billing.fix_or_var %></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillingManager</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= favicon_link_tag asset_path('favicon.ico') %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <% if login? %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <h3><%= current_user.name %></h3>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= button_to "Edit Profile", edit_user_path(current_user), method: :get, class:"btn nav-link"%>
            </li>
            <li class="nav-item active">
              <%= button_to "Check Billings", user_path(current_user), method: :get, class:"btn nav-link"%>
            </li>
          </ul>
          <span class="navbar-text">
            <%= button_to "Logout", logout_path, method: :delete, class:"btn btn-primary" %>
          </span>
        </div>
      </nav>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/types/new.html.erb
<h2>New Billing Type</h2>
<%= form_for @type do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
    <h3><%= pluralize(@type.errors.count, "error") %> prohibited this user from being saved:</h3>
    <ul>
      <% @type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    </div>
  <% end %>

<div class="field_with_errors">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div class="submit">
  <%= f.submit "Submit" %>
</div>
<% end %>

app/views/users/edit.html.erb
<div class="container-fluid">
  <div class="d-flex justify-content-center login">
    <div class="border">
      <div class="form-header">
        <h4>Edit Profile</h4>
      </div>
      <%= form_for @user do |f| %>
        <% if @user.errors.any? %>
          <div id="error_explanation">
          <h3><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
          </div>
        <% end %>

      <div class="field_with_errors form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class:"form-control" %>
      </div>
      <div class="field_with_errors form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class:"form-control" %>
      </div>

      <div class="submit">
        <%= f.submit "Confirm", class:'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container-fluid">
  <div class="d-flex justify-content-center login">
    <div class="border">
      <div class="form-header">
        <h4>Sign Up</h4>
      </div>
      <%= form_for @user do |f| %>
        <% if @user.errors.any? %>
          <div id="error_explanation">
          <h3><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
          </div>
        <% end %>

      <div class="field_with_errors form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class:"form-control"%>
      </div>
      <div class="field_with_errors form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class:"form-control" %>
      </div>
      <div class="field_with_errors form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class:"form-control" %>
      </div>
      <div class="field_with_errors form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class:"form-control" %>
      </div>
      <div class="submit">
        <%= f.submit "Sign Up", class:'btn btn-primary'%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="table-responsive">
    <table class="table table-light table-bordered">
      <thead class="thead-dark">
        <tr>
          <th>Date</th>
          <th>Fix_or_Var</th>
          <th>Detail</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        <% current_user.billings.each do |billing| %>
          <tr>
            <td><%= billing.date %></td>
            <td><%= billing.fix_or_var %></td>
            <td><%= button_to "detail", billing_path(billing), method: :get, class:'btn btn-success' %></td>
            <td><%= button_to "Edit", edit_billing_path(billing), method: :get, class:'btn btn-warning'%></td>
            <td><%= button_to "Delete", {:controller => :billings,
              :action => 'destroy', :id => billing.id }, method: :delete, class:'btn btn-danger' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <!-- Billing Buttons -->

  <!-- create -->
    <div>
      <%= button_to "Add a billing", new_billing_path, method: :get, class:"btn btn-primary btn-block" %>
    </div>
</div>